### PR TITLE
feat(error): add some colors to error messages

### PR DESCRIPTION
**Pull request by stevemao**
Also remove unnecessary hack in cli

### CODE REVIEW

**Comment by nickbalestra** [comment]
@stevemao I guess this need to be rebased before we can merge it...

**Comment by stevemao** [comment]
This module will be rewritten I believe? When that happens can we take this into account?

**Comment by Garbee** [comment]
Yea, I'll make sure this chalk thing is in v2. It provides very nice output. The CLI should be mostly the same when I'm done really. It's mostly the internals to the rest of the system that's going to take advantage of other libraries and be cleaned up.

**Comment by Garbee** [comment]
Since we are deprecating this library, closing this out. Commitlint already has pretty output in place.

**Pull request closed without merging**
