### PR TITLE
test: add test for optional scope

### PR DESCRIPTION
**Pull request by adjohnson916**
Adds a test to prove optional scope is supported. Probably this should be added in documentation as well.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Cool! Could you add the docs too?

**Comment by Garbee** [comment]
This is essentially duplicating [https://github.com/adjohnson916/validate-commit-msg/blob/d3e81f2c4505a56937819c7b84c2b540613651fb/test/validateMessage.test.js#L237](should allow empty scope). Perhaps if this is added to the top then the allowing empty should be removed since it is the same test coverage?

**Comment by adjohnson916** [comment]
@Garbee Ah I didn't notice that existing test. We could close the PR if you wish.

**Comment by kentcdodds** [comment]
Thanks. Yeah, we'll go ahead and close this one. Thanks!

**Comment by adjohnson916** [comment]
For docs, see #67.

**Pull request closed without merging**
